name: Github Pages Astro CI

on:
  # trigger workflow on every push to `main`
  push:
    branches: [main]
  # allow running workflow manually from Actions tab on GitHub
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    permissions:
      contents: write

    steps:
      - name: check out repository
        uses: actions/checkout@v2

      - name: set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm i

      - name: build astro site
        run: pnpm build
        working-directory: website-astro

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website-astro/dist
